### ISSUE TITLE
Camera calibration for the image set?

### ISSUE THREAD

**Issue by cdw** [FarmBot-Labs/garden-surface-data#1]
Hi hi!

Is the camera calibration generated by [this process](https://software.farm.bot/v14/The-FarmBot-Web-App/photos/camera-calibration.html) available for these images?

**Comment by RickCarlino** [comment]
@cdw I can update the repo this week with that information. It's important to note that the data will be specific to the device that took the photos (every device has different values) and cannot be generalized across devices.

Speak soon!

**Comment by RickCarlino** [comment]
@cdw Here is the calibration data- does this work for what you are trying to do?

![Camera calibration info](https://user-images.githubusercontent.com/1388608/140334556-b6c01465-6e03-4dd3-a6f4-492bc14ab0b8.png)
| Name | Value |
|--|--|
|Camera offset X|50|
|Camera offset Y|100|
|Origin location|Top right|
|Pixel coordinate scale|0.555|
|Camera rotation|83.23|

**Comment by cdw** [comment]
Thanks @RickCarlino! This is certainly useful! What I thought might be present was a camera calibration matrix of the [kind described here](https://docs.opencv.org/3.4.15/dc/dbb/tutorial_py_calibration.html). These contain camera focal length and distortion measurements. Typically you calculate them from a set of images of a calibration image like the one on FarmBot's calibration card or a checkerboard card.

If that isn't part of the current calibration process, we could generate them from, say, 7-10 images of the calibration card in a couple of different orientations and tilts. [Here](https://learnopencv.com/wp-content/uploads/2020/02/calibration-patterns.gif) is an example of a set of images. This lets you get better or more accurate 3d reconstruction with the traditional photogrammetry approach. Want to try to capture them?

**Comment by RickCarlino** [comment]
Sure, I can do a circle around the calibration card and snap some photos if you would like. Doing tilts would be tricky since the camera is bolted to the tool mount. I will post them in the next few days. Speak soon.

**Comment by RickCarlino** [comment]
@cdw Quick update:

I went out to the garden this morning to take a circle of photos around the calibration card. Unfortunately, it was too sunny. I am going to take the photos again at night (FarmBot has an LED strip).

I forgot to ask: do you need X/Y/ground distance labels for this data set?

**Comment by cdw** [comment]
@RickCarlino Excellent! I don't need X/Y/ground distance labels. But what would be great is if you can do it with the card propped up in a few orientations. Maybe with a rock under a couple of corners? That will simulate the tilting and let me do the calibration. I tested out the OpenCV workflow with some images from a cheap borescope camera I have locally [and it seems to work](https://gist.github.com/cdw/0f7776b58ed6e94c19b00b994f2f8847). 

Absolutely no hurry on any of this btw :-) It can totally wait a week or what have you.

**Comment by RickCarlino** [comment]
How do these look, @cdw ? Unfortunately, it's not a very wide angle lens:

![image](https://user-images.githubusercontent.com/1388608/140627377-96e9fe6e-ed00-4843-a1b0-406aa8e35f2a.png)
![image](https://user-images.githubusercontent.com/1388608/140627378-b9c123ab-306b-4f07-92c5-7fe1d14c020b.png)
![image](https://user-images.githubusercontent.com/1388608/140627381-38cdd884-b203-422f-b2c8-3428b3fdba07.png)
![image](https://user-images.githubusercontent.com/1388608/140627383-673506a1-9e11-4f50-83be-2a5269133569.png)
![image](https://user-images.githubusercontent.com/1388608/140627387-30e694a2-fc1b-456f-baef-50a8af5e2371.png)
![image](https://user-images.githubusercontent.com/1388608/140627390-90237835-634d-4a4c-bcc9-4b1a4210a6bb.png)
![image](https://user-images.githubusercontent.com/1388608/140627396-fddcb891-e9e6-481f-bb8b-b06f8b406e14.png)

**Comment by RickCarlino** [comment]
Whoops- Just realized I had a setting enabled that added some cropping to the images. Let me take another set of images without that setting enabled.

**Comment by RickCarlino** [comment]
![](https://storage.googleapis.com/farmbot-production/uu11ssxl941bp5u50b19aifqo7l5)
![](https://storage.googleapis.com/farmbot-production/8orn7hnm2msiw35goi4hjsn6q1ny)
![](https://storage.googleapis.com/farmbot-production/o8zidl29oh4u9yqsry6i93x1ab7n)
![](https://storage.googleapis.com/farmbot-production/xr4kt6giw4bss8gluq3yyagje0dw)
![](https://storage.googleapis.com/farmbot-production/j7io3trjf0da2hk1owmvxxob7ibq)
![](https://storage.googleapis.com/farmbot-production/ckqi9zzdsrdeqjq0gq0bg9zpos4c)
![](https://storage.googleapis.com/farmbot-production/3yjazedha210masp09vs0q31fj9z)

**Comment by RickCarlino** [comment]
![](https://storage.googleapis.com/farmbot-production/au379r1as03zmjqjnsspqa6fmm0t)
![](https://storage.googleapis.com/farmbot-production/gc3kpvn9cb6kyn3frpbuua2ign6w)
![](https://storage.googleapis.com/farmbot-production/fj72b2fw6df503zyifnr3qqt71k2)
![](https://storage.googleapis.com/farmbot-production/05qe6arg48acgl7a1g61l2sjilt0)

**Comment by cdw** [comment]
Hi @RickCarlino! I set up everything to work with this camera and this card [over here](https://gist.github.com/cdw/b00435a8e3078c93e6d9eb877d612816). It works, but that likely isn't a good calibration because there isn't much change in the plane of the calibration card and it doesn't cover enough of the image sensor. What you ideally want is thorough coverage of the field of view (as visualized by the detected point plot in the gist) and in/out of plane variation to capture different distortions. 

All that said, this doesn't look to have too much distortion! We can try out various approaches assuming zero distortion and shoo for a fully calibrated system later.
